name: follow-feeds

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  follow-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    #- uses: DeterminateSystems/magic-nix-cache-action@main
    - name: follow-feeds
      env:
        SLACK_URL: ${{ secrets.SLACK_URL }}
      # Reference `cli` tag which contains most recent code version
      # without extra update commits.
      run: nix run github:noblepayne/pinboard-poster/cli
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Updating database."
        file_pattern: "db"
